spring:
  application:
    name: gateway
server:
  port: 9090
  ssl:
    key-store: file:/keystore.p12
    key-store-password: IpnUpiita2024!
    key-store-type: PKCS12
    key-alias: spring-boot

eureka:
  instance:
    ip-address: 158.23.81.1 #158.23.81.1
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.1:8761/eureka #http://158.23.81.1:8761/eureka

config:
  url: http://158.23.81.1:8081/auth/validate?token=

