spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # Ruta para msvc-authms
        - id: msvc-authms
          uri: lb://msvc-authms
          predicates:
            - Path=/auth/**
        
        # Ruta para userms
        - id: userms
          uri: lb://userms
          predicates:
            - Path=/user/**
        
        # Ruta para cvms
        - id: cvms
          uri: lb://cv
          predicates:
            - Path=/cv/**
       

server:
  port: 9090

eureka:
  instance:
    ip-address: 158.23.81.168
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.168:8761/eureka

config:
  url: http://158.23.81.168:8081/auth/validate?token=
