spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: msvc-authms
            uri: lb://msvc-authms
            predicates:
              - Path=/auth/**
          - id: userms
            uri: lb://userms
            predicates:
              - Path=/user/**
          - id: cvms
            uri: lb://cvms
            predicates:
              - Path=/cv/**
server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.168:8761/eureka
config:
  url: http://158.23.81.168:8081/auth/validate?token=           
