spring:
  application:
    name: gateway

server:
  port: 9090
  ssl:
    key-store: file:/nuevo-certificado.p12
    key-store-password: IpnUpiita2024!
    key-store-type: PKCS12
    key-alias: spring-boot-cert
logging:
  file:
    name: ./logs/msvc-gateway-${date:yyyy-MM-dd}.log # Archivo con fecha en el nombre

eureka:
  instance:
    ip-address: 158.23.81.23
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.23:8761/eureka

config:
  url: http://158.23.81.23:8081/auth/validate?token=
